version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - graphviz
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements-docs.txt

sphinx:
  configuration: docs/conf.py

formats: all
