# layout: dagre

direction: right

Categories: {
  Regular: {shape: oval}
}

Areas: {
  Area 1: {
    Seat Regular: {label: "80 × Seat Regular"; shape: oval}
  }
}

Areas.Area 1.Seat Regular -> Categories.Regular: has category
