vars: {
  d2-config: {
    layout-engine: elk
    theme-id: 104
  }
}

classes: {
  entity: {
    shape: oval
    height: 80
  }
}

direction: right

container: "" {
  Ticket Categories: {
    Regular: { class: entity }
    Premium: { class: entity }
    VIP: { class: entity }
  }

  Seating Areas: {
    Area 1: {
      Seat Regular: {
        class: entity
        label: "1200 × Regular Seat"
      }
    }
    Area 2: {
      Seat Regular: {
        class: entity
        label: "400 × Regular Seat"
      }
      Seat Premium: {
        class: entity
        label: "150 × Premium Seat"
      }
    }
    Area 3: {
      Seat Regular: {
        class: entity
        label: "600 × Regular Seat"
      }
      Seat Premium: {
        class: entity
        label: "250 × Premium Seat"
      }
      Seat VIP: {
        class: entity
        label: "10 × VIP Seat"
      }
    }
  }

  Seating Areas.Area 1.Seat Regular -> Ticket Categories.Regular: has category
  Seating Areas.Area 2.Seat Regular -> Ticket Categories.Regular
  Seating Areas.Area 2.Seat Premium -> Ticket Categories.Premium
  Seating Areas.Area 3.Seat Regular -> Ticket Categories.Regular
  Seating Areas.Area 3.Seat Premium -> Ticket Categories.Premium
  Seating Areas.Area 3.Seat VIP -> Ticket Categories.VIP
}
